<?php namespace ProcessWire;

/**
 * PrivacyWire
 * This module adds management options for GDPR-relevant elements (loading maps, videos etc. only after accepting
 * external media) and cookies.
 *
 * @author blaueQuelle
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */
class PrivacyWire extends WireData implements Module, ConfigurableModule
{

    public static function getModuleInfo()
    {
        return [
            'title' => "PrivacyWire",
            'summary' => "This module adds management options for GDPR-relevant elements (loading maps, videos etc. only after accepting external media) and cookies.",
            'author' => "blaueQuelle",
            'href' => "https://github.com/blaueQuelle/privacywire",
            'version' => 25,
            'autoload' => true,
            'singular' => true,
            'requires' => ["PHP>=7.2", "ProcessWire>=3.0.110"],
            'installs' => ["TextformatterPrivacyWire"],
            'icon' => 'eye-slash'
        ];
    }

    public function ready()
    {
        if (
            $this->wire('page')->template == 'admin' || // exclude admin pages
            $this->wire('page')->template == 'form-builder' // exclude from form-builder iframe
        ) {
            return;
        }

        $this->addHookAfter('Page::render', $this, 'render');
    }

    public function ___render(HookEvent $event)
    {

        $respectDNT = ($this->respectDNT) ? "1" : "0";

        $customJsFunction = (!empty($this->trigger_custom_js_function)) ? $this->wire('sanitizer')->text($this->trigger_custom_js_function) : "";

        $messageTimeout = ($this->messageTimeout && intval($this->messageTimeout) > 1) ? intval($this->messageTimeout) : 1500;

        $jsFilePath = ($this->add_basic_css_styling) ? $this->wire('config')->urls->$this . "js/PrivacyWire.js" : $this->wire('config')->urls->$this . "js/PrivacyWireUnstyled.js";

        $output = wireRenderFile($this->wire('config')->paths->$this . 'PrivacyWireBanner.php', ['module' => $this]);
        $output .= '<script>var PrivacyWireSettings={version:"' . $this->version . '",dnt:"' . $respectDNT . '",customFunction:"' . $customJsFunction . '", messageTimeout:"' . $messageTimeout . '"};</script>';
        if ($this->use_procache_minification && $this->wire('modules')->isInstalled('ProCache') && $this->wire('modules')->get('ProCache')) {
            $output .= "<script defer src='{$this->wire('modules')->get('ProCache')->js($jsFilePath)}'></script>";
        } else {
            $output .= "<script defer src='{$jsFilePath}'></script>";
        }

        $event->return = str_replace("</body>", "{$output}</body>", $event->return);
    }

    public function ___install()
    {
    }

    public function ___uninstall()
    {
    }


}
